In [19]:
import verification as vf
dataFrameChanged, dataFrame = vf.verifyPark("NAVA", color=True)

In [20]:
dataFrameChanged

In [21]:
dataFrame

   UnitCode    Field                                      Label    Code  \
0      NAVA    Input  BEGINNING TRAFFIC COUNT AT VISITOR CENTER      F1
1      NAVA    Input                  A/V HISATSIMON ATTENDANCE     F10
2      NAVA    Input                   A/V BETATAKIN ATTENDANCE     F12
3      NAVA    Input                  A/V LASER SHOW ATTENDANCE    F12B
4      NAVA    Input            NAVAJO BASKETRY FILM ATTENDANCE    F12C
..      ...      ...                                        ...     ...
68     NAVA  Formula                  Rec Visitor Hours Arizona  TRVHAZ
69     NAVA  Formula                                       TRVS    TRVS
70     NAVA  Formula               NPS CG RV Overnights Arizona  TRVSAZ
71     NAVA  Formula                                         TT      TT
72     NAVA  Formula             NPS CG Tent Overnights Arizona    TTAZ

    INSTATS    REC   RECH   NREC  NRECH     CL    CCG     BC     TT   TRVS  \
0      True   True   True  False  False  False  False  False  False  False
1     False  False  False  False  False  False  False  False  False  False
2     False  False  False  False  False  False  False  False  False  False
3     False  False  False  False  False  False  False  False  False  False
4     False  False  False  False  False  False  False  False  False  False
..      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
68    False  False  False  False  False  False  False  False  False  False
69     True  False  False  False  False  False  False  False  False  False
70    False  False  False  False  False  False  False  False  False  False
71     True  False  False  False  False  False  False  False  False  False
72    False  False  False  False  False  False  False  False  False  False

     MISC   NROS
0   False  False
1   False  False
2   False  False
3   False  False
4   False  False
..    ...    ...
68  False  False
69  False  False
70  False  False
71  False  False
72  False  False

[73 rows x 16 columns]